language: dart
dart:
  - stable
with_content_shell: true
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: ./tool/travis.sh
env:
  - DARTANALYZER_FLAGS=--fatal-warnings
