name: ose
version: 0.0.1
description: >
  Outspace engine is 2d game engine.
author: Andy Tyurin <andy.tyurin@gmail.com>
homepage: http://os-engine.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  vector_math: '>=2.0.0'
  uuid: '^0.5.2'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  browser: "^0.10.0+2"
