name: ose
version: 0.0.2
description: >
  OS Engine.
author: Andy Tyurin <andy.tyurin@gmail.com>
homepage: http://os-engine.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  uuid: '^0.5.2'
  logging: '^0.11.3'
  meta: '^1.0.1'

dev_dependencies:
  browser: "^0.10.0+2"
